import type { Metadata } from "next";
import "./globals.css";
import { nunito } from "./fonts";
import { MenuProvider } from "./context/MenuContext";


export const metadata: Metadata = {
  title: "Axiora App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MenuProvider>
      <body className={nunito.className}>
        {children}</body>
      </MenuProvider>
    </html>
  );
}
