import type { Metadata } from "next";
import "./globals.css";
import Menu from "./components/Menu";
import { nunito } from "./fonts";


export const metadata: Metadata = {
  title: "Axiora App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Menu />
        {children}</body>
    </html>
  );
}
