version: 0.2

phases:
  install:
    commands:
      # Install Node 14
      - echo Installing node 14...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      # Install dependencies
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      # tests
      # build
      - echo Building...
      - npm run build:dev
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
